version: '3.9'

services:
  home_finance_api:
    container_name: home_finance_api
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - home_finance_db
    links:
      - home_finance_db
    networks:
      - home-finance-network
    environment:
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  home_finance_db:
    image: mysql:latest
    container_name: home_finance_db
    mem_limit: 384m
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
    networks:
      - home-finance-network

networks:
  home-finance-network:
    external: true
