version: '3.9'

services:
  home_finance_api:
    container_name: home_finance_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - home_finance_db
    links:
      - home_finance_db
    networks:
      - home-finance-network
    environment:
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=pgsql
      - DB_HOST=home_finance_db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  home_finance_db:
    image: postgres:latest
    container_name: home_finance_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
    networks:
      - home-finance-network

networks:
  home-finance-network:
    external: true
