version: '3.9'

services:
  home_finance_api:
    container_name: home_finance_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
      - 8000:8000
    depends_on:
      - home_finance_db
    links:
      - home_finance_db

  home_finance_db:
    image: mysql:5.7
    container_name: home_finance_db
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
networks:
  default:
    external:
      name: home-finance-network
