@host = http://localhost:8000/api
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzBiZTQxZTI2MTdlODAxNzE0YmU3ODRjY2UyNjVmZGJkMzEzMzFjNTlkNjk1Y2RmOGRiMjdjZjA3ZGM0OTk4NmY0Zjc0NzZiN2ZhMGEwZTYiLCJpYXQiOjE2NjA4NDQzMDguNDgwMTkyLCJuYmYiOjE2NjA4NDQzMDguNDgwMTk3LCJleHAiOjE2OTIzODAzMDguNDcxMzE2LCJzdWIiOiI1Iiwic2NvcGVzIjpbXX0.EgQwLpBM0wx7t4p0oG78vFt0Yp9vewNENDdp24BThLSe9Fd9r9ijxLoHkA2d-QkrTLNVZHs0nAb6tzgqaTobicfM63VAZNVQg1rqSnt_3rpnYxqI6OkVbpnnnUX0ohGTZuQdkKGMFgQnJdY9Y1R1fWpQW7mX1QwSgEMdlZ1FqyUw5tKwa1LtE67TEbXamU8KLlZzDwpse9DyD3oCJVggT3xwTEYAyHsUme6Vso1ZY3IdQvZFMCUkFbjzGNKuXWV_dmDPp_173Ii1EyWKbpySei6eoRms3Ey6r4dPPgUVW1yozGbPhNeJJv4N1EYfkrtDNfW9ss6fboVhUJAJ3fVdhH4B8LfserN7icSzINICYydyIy7X13U0djLuNsFch-MoFk8YmGeMUZF-NnxSC0kJe2t5eqBVdbC6cLgFUIIJOZ53A7vGcfihTdXtZqo3o6daHGRu6ZENWHq_IRna1Ox5t8y3vgbOYwGacN8Te-HTb1AT6YgayNlYtEf_99rYYqPJwjLiEKUn05ydjfjH2FahwrrBiz6w2uPg3b28LEUSg1uVUdeJazrbgblfPu-5ctCzDWmbRKxAeDEQEALJPVUI6viWdfstmR3PLMVBpYEnwbH5SU3D5DwPhA-mI-O1vS5N4SrZK-HwVyBAz0ePtup2q9tnvTHYhzh6E64FYAHbCHc


### REGISTER USER
POST {{host}}/register HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
    "name": "test",
    "email": "test234@test.com",
    "password": "testeeeeeeeee",
    "password_confirmation": "testeeeeeeeee"
}


### LOGIN
POST {{host}}/login HTTP/1.1
content-type: application/json
X-Requested-With: XMLHttpRequest

{
    "email": "test2@test.com",
    "password": "testeeeeeeeee"
}


### LOGOUT
POST {{host}}/logout HTTP/1.1
Authorization: {{token}}
content-type: application/json
X-Requested-With: XMLHttpRequest


### RETURN USER DETAILS
GET {{host}}/me HTTP/1.1
Authorization: {{token}}
content-type: application/json
X-Requested-With: XMLHttpRequest
